(function(){function y(){m=+new Date;for(var a=0;a<d.length;a++)d[a].think()}function z(){m=+new Date;b.clearRect(0,0,e.width,e.height);var a=null!=c?c.x-100:0;g=0==g?a:Math.round((g+a)/2);for(a=-(Math.floor(g/2)%288);a<e.width;)b.drawImage(l,0,0,288,512,a,0,288,512),a+=288;b.save();b.translate(-g,0);for(a=0;a<n.length;a++)n[a].draw();b.restore();for(a=-(Math.floor(g)%336);a<e.width;)b.drawImage(l,584,0,336,111,a,401,336,111),a+=336;b.save();b.translate(-g,0);for(a=0;a<d.length;a++)d[a]!=c&&d[a].draw();
null!=c&&c.draw();b.restore();b.fillText("Score: "+J()+" | Players: "+A+" | Distance: "+(null==c?0:Math.floor(c.x/200)),20,20);u.clearRect(0,0,e.width,e.height);u.drawImage(r,0,0,e.width,e.height);window.requestAnimationFrame(z)}function J(){if(null==c)return 0;for(var a=0,p=0;p<n.length;p++)n[p].x<v||c.x>n[p].x+30&&++a;return a}function B(a,p,b,c){this.id=a;this.x=p;this.y=b;this.vx=C;this.vy=0;this.seed=9999*Math.random();this.sx=p;this.sy=b;this.fx=p;this.fy=b;this.nick=c}function D(a,b){this.x=
a;this.y=b}function K(){if(null!=c&&(~~c.x!=E||~~c.y!=F)){var a=new ArrayBuffer(9),b=new DataView(a);b.setUint8(0,1);b.setInt32(1,~~c.x,!0);b.setInt32(5,~~c.y,!0);h.send(a);E=c.x;F=c.y}}function t(){var a=q.value,b=new ArrayBuffer(32),c=new DataView(b);c.setUint8(0,5);for(var d=0;d<a.length&&16>d;d++){var f=a.charCodeAt(d);128<=f||c.setUint8(d+1,f)}h.send(b)}function G(a,b){return a.x+a.r<b.x||a.y+a.r<b.y||a.x-a.r>b.x+b.width||a.y-a.r>b.y+b.height?!1:!0}window.onload=function(){q=document.getElementById("nickname");
q.onchange=t;q.onkeydown=t;q.onkeyup=t;q.onkeypress=t;e=document.getElementById("canvas");u=e.getContext("2d");r=document.createElement("canvas");r.width=e.width;r.height=e.height;b=r.getContext("2d");var a="ws://localhost:2828",a=H[~~(H.length*Math.random())];h=new WebSocket(a);h.binaryType="arraybuffer";h.onopen=function(a){console.log("Socket connected")};h.onmessage=function(a){a=a.data;switch((new DataView(a)).getUint8(0)){case 0:I=(new DataView(a)).getInt32(1,!0);break;case 1:a=new DataView(a);
for(var b=0;b<d.length;b++)d[b].wasSeen=!1;A=a.getInt32(1,!0);for(var e=a.getInt32(5,!0),f=9,b=0;b<e;b++){for(var g=a.getInt32(f+0,!0),l=a.getInt32(f+4,!0),m=a.getInt32(f+8,!0),f=f+12,h="";;){var k=a.getUint8(f++);if(0==k)break;h+=String.fromCharCode(k)}k=w[g];null==k?(k=new B(g,l,m,h),d.push(k),w[g]=k,k.id==I&&null==c&&(c=k)):(k.wasSeen=!0,k.update(l,m,h))}for(b=0;b<d.length;b++)null==d[b].id||d[b].wasSeen||(delete w[d[b].id],d[b].destroy(),d.splice(b,1),--b);e=a.getInt32(f,!0);f+=4;for(b=0;b<e;b++)n.push(new D(a.getInt32(f+
0,!0),a.getInt32(f+4,!0))),f+=8}};y();z();setInterval(y,1E3/60);setInterval(K,50)};var e,r,b,u,l=new Image;l.src="atlas.png";var g=0,d=[],w={},n=[],m=0,c=null,x=!1,I=null,s=!1,A="?",v=100,q,C=2,h,H=["ws://flapmmo.com:2828","ws://flapmmo.com:2829","ws://flapmmo.com:2830"];B.prototype={id:0,x:0,y:0,vx:0,vy:0,seed:0,wasSeen:!0,nick:null,rotation:0,targetRotation:0,sx:0,sy:0,fx:0,fy:0,start:0,end:0,draw:function(){b.save();b.translate(2*Math.floor(this.x/2),2*Math.floor(this.y/2));var a=Math.floor((m+
this.seed)/200)%2;b.rotate(this.rotation);this==c?(b.beginPath(),b.fillStyle="rgba(255, 255, 255, 0.5)",b.arc(0,0,30,0,2*Math.PI,!1),b.fill(),b.drawImage(l,230,762+52*a,34,24,-17,-12,34,24)):(b.globalAlpha*=0.5,b.drawImage(l,6+56*a,982,34,24,-17,-12,34,24),b.globalAlpha/=0.5);b.rotate(-this.rotation);if(a=this.nick)b.textAlign="center",b.fillStyle="#000000",b.fillText(a,1,-20),b.fillText(a,-1,-20),b.fillText(a,0,-21),b.fillText(a,0,-19),b.fillStyle="#FFFFFF",b.fillText(a,0,-20);b.restore()},think:function(){if(this==
c){for(var a=0;a<n.length;a++)if(n[a].collidesWith(this)){s=!0;break}this.vy+=0.4;389<=this.y&&(this.vy=this.vx=0,s=!0);s?(this.vx=0,389<this.y&&(this.y=389)):x&&(x=!1,this.vy=-8);this.x+=this.vx;this.y+=this.vy;this.targetRotation=Math.atan2(this.vy,this.vx)}else a=(m-this.start)/(this.end-this.start),1<a&&(a=1),this.x=this.sx+(this.fx-this.sx)*a,this.y=this.sy+(this.fy-this.sy)*a,this.targetRotation=Math.atan2(this.fy-this.sy,this.fx-this.sx);for(;180<this.targetRotation;)this.targetRotation-=360;
for(;-180>this.targetRotation;)this.targetRotation+=360;this.rotation=(this.rotation+this.targetRotation)/2},update:function(a,b,d){this!=c&&(this.sx=this.x,this.sy=this.y,this.fx=a,this.fy=b,this.start=m,this.end=m+200);d&&(this.nick=d)},destroy:function(){}};D.prototype={x:0,y:0,getHeight:function(){return 124},draw:function(){this.isValid()||(b.globalAlpha*=0.5);b.drawImage(l,112,646,52,320,this.x,this.y-320,52,320);b.drawImage(l,168,646,52,320,this.x,this.y+this.getHeight(),52,320);this.isValid()||
(b.globalAlpha/=0.5)},collidesWith:function(a){return this.isValid()?G({x:a.x,y:a.y,r:12},{x:this.x,y:this.y-320,width:52,height:320})||G({x:a.x,y:a.y,r:12},{x:this.x,y:this.y+this.getHeight(),width:52,height:320}):!1},isValid:function(){return this.x>v+200}};var E,F;document.body.onkeydown=function(a){s&&(null==c||389<=c.y)?null!=c&&(c.vx=C,c.vy=0,c.x=100,c.y=50,v=c.x,s=!1):null!=c&&0<c.y&&(x=!0)};window.requestAnimationFrame=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||
function(a){setTimeout(a,1E3/60)}})();
