#!/bin/sh

YELLOW=\\e[1m\\e[33m
RESET=\\e[m

function reconfirm()
{
    lastIndex=$#
    if [ ${lastIndex} -eq 1 ]; then
        exit 0
    fi

    flag=0
    for((i=1; i<=$#; ++i))
        do  
            if [ ${!i} = "-h" -o ${!i} = "--help" -o ${!i} = "--version" ]; then
                flag=2
                break 
            elif [ ${!i} = "--non-interactive" ]; then
                flag=1
            fi  
        done  

    if [ ${flag} -eq 0 ]; then
        operation=${!lastIndex}
        opName=`echo ${operation}|awk -F "=" '{print $1}'|tr -d '-'`
        opValue=`echo ${operation}|awk -F "=" '{print $2}'`
        opValue=${opValue//'.'/' '}
  
        if [ "x${opName}" = "xoperation" -a "x${opValue}" != "x" ]; then
            echo -e "${opValue}! Sure to continue? (y/n)"
        else
            echo -e "Sure to continue? (y/n)"
        fi

        read ANSWER;
        if [ "x${ANSWER}" != "xy" -a "x${ANSWER}" != "xY" ]; then
            echo -e "${YELLOW}Operation Cancel!$RESET\n"
            exit 1
        fi
    fi
}

reconfirm $*
exit 0
